server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/Rene/Documents/rene/inflearn/msa-with-springcloud-config
