server:
  port: 8761

spring:
  application:
    name: discoveryservice

# 기본값은 true 이기 때문에 eureka server는 서버 역할만 하고 스스로를 등록하지 않도록 false 설정
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
