server:
  port: 8761

spring:
  application:
    name: discoveryservice


#false ??? ?? ??? ??? ??? ???? ???? ??? ??
#=> ???? ??? ?? ?? ??? ???? ?? ?? ?? false ??
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
